"""Write the server side of the Ogre spells (spell_dbc rows) from ogre_spells.py, and of the Brute's talent trees
(talent_dbc, talenttab_dbc rows) from ogre_talents.py.

Usage:
  python gen_spell_sql.py --dbc "<server data dir>/dbc/Spell.dbc" [--db host:port:user:password:database]

The spell_dbc column names are read from the world database so the rows follow its exact layout. Talent.dbc is
read next to the given Spell.dbc.
"""

import argparse
import os

import mysql.connector

import ogre_spells
import ogre_talents

HERE = os.path.dirname(os.path.abspath(__file__))
SQL_DIR = os.path.join(HERE, "..", "..", "data", "sql", "db-world", "base")
OUT = os.path.join(SQL_DIR, "mod_two_headed_ogre_spells.sql")
TALENTS_OUT = os.path.join(SQL_DIR, "mod_two_headed_ogre_talents.sql")
TALENT_RESET_OUT = os.path.join(HERE, "..", "..", "data", "sql", "db-characters", "base",
                                "mod_two_headed_ogre_talent_reset.sql")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dbc", required=True, help="server Spell.dbc (3.3.5a)")
    parser.add_argument("--db", default="127.0.0.1:3307:acore:acore:acore_world")
    args = parser.parse_args()

    host, port, user, password, database = args.db.split(":")
    db = mysql.connector.connect(host=host, port=int(port), user=user, password=password, database=database)
    cursor = db.cursor()
    cursor.execute("SELECT COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = %s AND "
                   "TABLE_NAME = 'spell_dbc' ORDER BY ORDINAL_POSITION", (database,))
    rows = cursor.fetchall()
    columns = [row[0] for row in rows]
    unsigned = {index for index, row in enumerate(rows) if "unsigned" in str(row[1])}

    with open(args.dbc, "rb") as handle:
        spell_dbc = handle.read()

    lines = [
        "-- mod-two-headed-ogre: the Ogre racial spells, server side (the client patch adds the same records).",
        "-- Generated by client/tools/gen_spell_sql.py from client/tools/ogre_spells.py.",
        "--   91050 Fureur bicéphale (active, 5 min): both heads act freely for 20 s (module).",
        "--   91051 Chute d'ogre (passive): no fall damage, impact on landing (module).",
        "--   91052 Chute d'ogre (impact): physical damage and knock back around the ogre, damage set by the module.",
        "--   91053-91072 the other racials, stances and their hidden auras; 91100-91316 the Brute's talent",
        "--   ranks, 91320-91329 the spells of its active talents and their helpers.",
    ]
    lines += ogre_spells.spell_dbc_sql(spell_dbc, columns, unsigned)
    with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    print("written", OUT)

    with open(os.path.join(os.path.dirname(args.dbc), "Talent.dbc"), "rb") as handle:
        talent_dbc = handle.read()
    lines = [
        "-- mod-two-headed-ogre: the Brute's talent trees, one per stance (MOI TAPER, MOI MAGIE, MOI ENCAISSER), in",
        "-- place of the Paladin's (the carrier class). The Paladin talent ids are reused, the ones left over emptied.",
        "-- Generated by client/tools/gen_spell_sql.py from client/tools/ogre_talents.py.",
    ]
    lines += ogre_talents.talent_sql(talent_dbc)
    with open(TALENTS_OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    print("written", TALENTS_OUT)

    lines = ["-- mod-two-headed-ogre: the Brute's talents replace the Paladin's",
             "-- (db-world mod_two_headed_ogre_talents.sql).",
             "-- Generated by client/tools/gen_spell_sql.py from client/tools/ogre_talents.py."]
    lines += ogre_talents.talent_reset_sql()
    with open(TALENT_RESET_OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    print("written", TALENT_RESET_OUT)


if __name__ == "__main__":
    main()
